### ISSUE TITLE
Как скомплировать твой проект

### ISSUE THREAD

**Issue by modeckrus** [MihailRis/VoxelEngine-Cpp#1]
Нет ни make ни cmake ни vs code ни launch.json, просто код. Тяжело скомпилироватб не зная как

**Comment by steelswing** [comment]
Кста зависимостей тоже нету

**Comment by steelswing** [comment]
Я собрал
![image](https://user-images.githubusercontent.com/53971838/130175714-cfc6e098-5202-4eed-b30d-6b09cf75f1f2.png)

**Comment by MihailRis** [comment]
Добавил makefiles для Debug конфигурации, сгенерированные Eclipse CDT на Linux. Позже сравню  с тем, как линкуются библиотеки на Windows и добавлю доп. конфигурацию для Windows

**Comment by linux-admin0001** [comment]
класс!

**Comment by MihailRis** [comment]
Добавил makefiles для Debug, сгенерированные на Windows

**Comment by MihailRis** [comment]
Добавил библиотеки для MinGW, исправил параметры линковки библиотек в makefiles. Скоро сделаю видео-инструкцию по сборке проекта через MinGW

**Comment by MihailRis** [comment]
Теперь через CMake
