### ISSUE TITLE
Не собирается на Arch Linux («luaL_openlib» was not declared in this scope;)

### ISSUE THREAD

**Issue by kortaol** [MihailRis/VoxelEngine-Cpp#110]
При попытке запустить `./run.sh` начинается сборка, которая обрывается на этом моменте: 
```
In file included from /home/kort/VoxelEngine-Cpp/src/logic/scripting/api_lua.cpp:1:
/home/kort/VoxelEngine-Cpp/src/logic/scripting/api_lua.h:7:57: замечание: «#pragma message: better use LuaJIT instead of plain Lua»
    7 | #pragma message("better use LuaJIT instead of plain Lua")
      |                                                         ^
/home/kort/VoxelEngine-Cpp/src/logic/scripting/api_lua.cpp: In function «int luaopen_world(lua_State*)»:
/home/kort/VoxelEngine-Cpp/src/logic/scripting/api_lua.cpp:50:5: ошибка: «luaL_openlib» was not declared in this scope; did you mean «luaL_openlibs»?
   50 |     luaL_openlib(L, "world", worldlib, 0);
      |     ^~~~~~~~~~~~
      |     luaL_openlibs
/home/kort/VoxelEngine-Cpp/src/logic/scripting/api_lua.cpp: In function «int luaopen_player(lua_State*)»:
/home/kort/VoxelEngine-Cpp/src/logic/scripting/api_lua.cpp:108:5: ошибка: «luaL_openlib» was not declared in this scope; did you mean «luaL_openlibs»?
  108 |     luaL_openlib(L, "player", playerlib, 0);
      |     ^~~~~~~~~~~~
      |     luaL_openlibs
make[2]: *** [CMakeFiles/VoxelEngine.dir/build.make:944: CMakeFiles/VoxelEngine.dir/src/logic/scripting/api_lua.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/VoxelEngine.dir/all] Ошибка 2
make: *** [Makefile:91: all] Ошибка 2
``` 
Попытка заменить `luaL_openlib` на `luaL_openlibs`, понятное дело, не помогла. 
**Upd:** установка `luajit` из репозитория extra, `luajit-git` из AUR или через команды из README также не помогли.
Немного о себе: 
- Arch Linux с ядром 6.6.8
- cmake версии 3.28.1
- Версия проекта: последняя, 0.17
- Что делал: просто запустил `./run.sh`

Не нашёл такой issue ранее, поэтому создаю новую. Если такая уже решена, пожалуйста, укажите.

**Comment by kortaol** [comment]
Я не заметил `+ install LuaJIT` в README.

**Comment by kortaol** [comment]
Установка LuaJIT через `yay` или через команды из README не помогла. Ошибка сохраняется

**Comment by Stomarver** [comment]
по моему проще appimage починить.

**Comment by kortaol** [comment]
Переустановил LuaJIT + собирал вечернее обновление, по итогу всё работает. Issue закрывать не буду, т.к. возможно только мне так повезло

**Comment by Lintech-1** [comment]
> Переустановил LuaJIT + собирал вечернее обновление, по итогу всё работает. Issue закрывать не буду, т.к. возможно только мне так повезло

Версия Appimage у меня запустилась с артефактами :) решил собрать из исходников и с первого раза у меня получилось, естественно предварительно установил нужные зависимости. Напишу по пунктам для понимая

Установка библиотек (на Wayland не проверял работу)
`sudo pacman -S glfw-x11 glew glm libpng openal`

Сборка LuaJIT (репозиторий скопировал в домашнюю директорию)
```
git clone https://luajit.org/git/luajit.git
cd luajit
make && sudo make install INSTALL_INC=/usr/include/lua
```

Финальная сборка
```
git clone https://luajit.org/git/luajit.git
cd luajit
make && sudo make install INSTALL_INC=/usr/include/lua
```

От себя могу добавить что если у вас карта Amd и сидите на Arch linux, то проверьте на наличие эти пакеты для видеокарты
`sudo pacman -Sy mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader mesa-vdpau lib32-mesa-vdpau libva-mesa-driver lib32-libva-mesa-driver vulkan-mesa-layers`

![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/81373196/d67f0816-0011-44f5-bc45-d5526e65aca5)

**Comment by InfiniteCoder01** [comment]
Я такую проблему решил следующим образом:
1. `git clone https://luajit.org/git/luajit.git && cd luajit && make && sudo make install PREFIX=/usr/lib/luajit`
2. В CMakeLists.txt, заменил `find_package(Lua REQUIRED)` на
```
include_directories("/usr/lib/luajit/include/luajit-2.1/")
set(LUA_LIBRARIES "/usr/lib/luajit/lib/libluajit-5.1.a")
```
3. `./run.sh`
