### ISSUE TITLE
Ошибка при генерации

### ISSUE THREAD

**Issue by Adionixitt** [MihailRis/VoxelEngine-Cpp#112]
Рядом с биомами деревьев иногда генерируется одиночный блок древесины
![Снимок экрана 2024-01-15 115435](https://github.com/MihailRis/VoxelEngine-Cpp/assets/113976836/db595421-c564-4c43-94e3-9d1b35816c8b)

**Comment by AlexXZero** [comment]
Есть информация как часто это происходит? Можешь скинуть сид и координаты?

**Comment by MihailRis** [comment]
Это пень. И он явно прописан в генераторе мира
