### ISSUE TITLE
Добавить консоль (чат)

### ISSUE THREAD

**Issue by RomanDonw** [MihailRis/VoxelEngine-Cpp#113]
Предлагаю сделать что-то типо чата из майна, но пока мультиплеера нет, чат будет использоваться для выполнения "консольных команд", которые можно будет биндить (назначать) через скрипты Lua.

**Comment by AlexXZero** [comment]
Поддерживаю, так же это может быть полезно для отладки (если добавить специальные команды для этого). Примером самых простых команд может быть: `fill x1 y1 z1 x2 y2 z2 block_type` и т.п.

**Comment by RomanDonw** [comment]
P.S. Могу помочь с созданием обработчика команд, только создайте всё необходимое для этого. Так же не помешало бы разобраться с исходниками и git-ом. Если кто-то хочет помочь, пожалуйста - мой ник в дс сервере по движку такой же, как и здесь.

**Comment by DSDemen** [comment]
могу зделать
