### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by AlexXZero** [MihailRis/VoxelEngine-Cpp#131]
**Опишите ошибку**
Тут сразу две проблемы: 
Не правильное отображение верхней грани блока на 256 высоте: она полностью прозрачна.

**Для воспроизведения**
Шаги для воспроизведения поведения:
1. Постройте столб высотой 255 блоков (256 блоков игра не позволяет построить столб просто так, возможно это другой баг)
2. Перейдите в режим полёта
3. Выровняйтесь со столбом находясь чуть выше его верхней повернхности (чтобы персонаж был примерно на 255 высоте)
4. Поставьте блок поверх 255 блока
5. Посмотрите на верхнюю грань этого блока

**Ожидаемое поведение**
Блок должен отрисовываться корректно.

**Скриншоты**
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/3096462/c6f3d302-a7e1-4596-8f3b-13f4c3ad6419)

**Техническая информация (заполните следующую информацию):**
  - ОС: linux
  - Версия 0.18

**Дополнительный контекст**
(отсутствует)

**Comment by MihailRis** [comment]
Вернул небесную твердь

Игрок и не должен выходить за пределы мира
