### ISSUE TITLE
Можно поставить факел за место травы, но это крайне неправильно

### ISSUE THREAD

**Issue by GreMirid** [MihailRis/VoxelEngine-Cpp#132]
Можно поставить факел боком об траву.

Шаги для воспроизведения поведения:
1. Создайте мир
2. Найдите траву
3. На стороне поставьте факел

По происшествию:
Трава исчезнет, факел появиться боком на месте травы.

![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/56092546/3175d454-9fd8-49fd-a00b-b05f364a141c)

Техническая информация: я думаю не имеет значения

**Comment by MihailRis** [comment]
Исправлено последним коммитом
