### ISSUE TITLE
WorldGen в контент-паках

### ISSUE THREAD

**Issue by InfiniteCoder01** [MihailRis/VoxelEngine-Cpp#147]
**Связан ли ваш запрос на добавление функции с проблемой? Пожалуйста, опишите.**
Хотелось бы иметь возможность влиять на генерацию мира из контент-паков

**Опишите желаемое решение**
С помощью шума перлина разбить мир на биомы. Выполнить LUA  функцию из файла для этого биома на каждом столбце в области биома. Добавить в стандартную библиотеку функции шума перлина и псевдослучайных чисел

**Comment by MihailRis** [comment]
Будет реализовано в одном из ближайших обновлений
