### ISSUE TITLE
Вода? 

### ISSUE THREAD

**Issue by InfiniteCoder01** [MihailRis/VoxelEngine-Cpp#149]
**Связан ли ваш запрос на добавление функции с проблемой? Пожалуйста, опишите.**
Сейчас, если в озере поставить любой блок, а затем убрать его - останется дыра

**Опишите желаемое решение**
Заполнение этой дыры.
Можно ещё текущую воду добавить

**Дополнительный контекст**
![screenshot-2024-02-18_17-07-22](https://github.com/MihailRis/VoxelEngine-Cpp/assets/66557254/ae051180-16d7-4bcb-8fd5-bd6491344b8c)

**Comment by rekvizitt** [comment]
скриншот сломанный

**Comment by InfiniteCoder01** [comment]
Спасибо, поправил

**Comment by Fidius-jko** [comment]
Заполнение дыры легче всего сделать через текучесть.

**Comment by Fidius-jko** [comment]
А текучесть вроде можно и модом добавить.

**Comment by MihailRis** [comment]
Жидкости на данный момент имеют невысокий приоритет, что вероятно изменится после того, как станут реализуемы игровые режимы.
