### ISSUE TITLE
Разрешает установку блоков, если возвращает ???

### ISSUE THREAD

**Issue by InfiniteCoder01** [MihailRis/VoxelEngine-Cpp#154]
**Опишите ошибку**
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/66557254/fdd4a854-5559-4792-811e-476666602f7e)
Разве не наоборот?
https://github.com/MihailRis/VoxelEngine-Cpp/wiki/%D0%A1%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B8%D0%BD%D0%B3#%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8F-%D0%B1%D0%BB%D0%BE%D0%BA%D0%BE%D0%B2

**Comment by MihailRis** [comment]
Исправил
