### ISSUE TITLE
`[string "res/layouts/inventory.xml.lua"]:2: inventory does not exists in runtime: 1`

### ISSUE THREAD

**Issue by InfiniteCoder01** [MihailRis/VoxelEngine-Cpp#155]
**Опишите ошибку**
При shift+click на предмете - выдаёт ошибку

**Для воспроизведения**
Шаги для воспроизведения поведения:
1. Откройте инвентарь
3. Нажмите Shift+Левая Клавиша Мыши на любом предмете 
5. См. ошибку

**Ожидаемое поведение**
Удаление предмета из инвенторя или перенос его в другой контейнер/хотбар

**Comment by MihailRis** [comment]
Исправлено
