### ISSUE TITLE
Не запускается на Windows 10

### ISSUE THREAD

**Issue by Wasdergingame** [MihailRis/VoxelEngine-Cpp#16]
Выдаёт четыре ошибки об отсутствии данных файлов: OpenAL32.dll, VCRUNTIME140D.dll, ucrtbased.dll

**Comment by clasher113** [comment]
Насчет OpenAL32.dll - https://www.openal.org/downloads/
Остальные dll насколько я знаю идут вместе с Visual Studio. Проблема в том что автор скомпилировал в debug конфигурации а не release как это нужно было

**Comment by MihailRis** [comment]
Обновил файл

**Comment by Wasdergingame** [comment]
Ничего не изменилось

**Comment by MihailRis** [comment]
Загружена новая версия

**Comment by MihailRis** [comment]
Ладно, сегодня протестирую на виртуалке
