### ISSUE TITLE
Размещение блоков зажатием клавиши

### ISSUE THREAD

**Issue by TysikGG** [MihailRis/VoxelEngine-Cpp#177]
Предлагаю добавить функцию размещения блоков не только кликом мыши, но и зажатием ПКМ. Это было бы очень удобно.

**Comment by InfiniteCoder01** [comment]
Есть незадокумментированая клавиша X

**Comment by TysikGG** [comment]
> Есть незадокумментированая клавиша X

да, но смысла нажимать отдельную кнопку нет, гораздо легче реализовать это как в обычном майнкравте
