### ISSUE TITLE
Поддержка Lua-функций взаимодействия с окном консоли движка

### ISSUE THREAD

**Issue by RomanDonw** [MihailRis/VoxelEngine-Cpp#187]
Местами, для дебаггинга модификаций и не только требуются дополнительные функции для работы с окном консоли, такие как:

read() -> string - читает строку до пробела, переноса строки или любого другого подобного разделительного символа, из консоли. Работает подобно scanf("%s", result) из C.

readline() -> string - аналогична read(), но читает всю строку до нажания на Enter (перенос строки). Работает подобно gets(result) из C.

write(string text) - выводит строку без вывода символа переноса строки. Подобна printf("%s", text) из C.

getCursorPosition() -> int x, int y - возвращает позицию курсора в консоли (столбец, строка).

setCursorPosition(int x, int y) - переводит курсор на указанные коордрнаты (столбец, строка). Если курсор переместить не удаётся, то он и не перемещается, ничего не происходит. Похожа на gotoxy(int x, int y) из C.

(ВНИМАНИЕ:ДАННЫЙ РАЗДЕЛ НЕ ДОПИСАН И БУДЕТ ДОПИСАН ПОЗЖЕ.)

**Comment by MihailRis** [comment]
В обновлении 0.21 уже запланировано добавление debug-консоли внутри движка
