### ISSUE TITLE
Во время компиляции связанная с LuaJIT ошибка

### ISSUE THREAD

**Issue by BopikQYVI** [MihailRis/VoxelEngine-Cpp#188]
Установил все пакеты, скомпилировал luajit(При этом luajit и lua установлены из репо). Компилирую и:
`In file included from /home/bopik/build/VoxelEngine-Cpp/src/assets/../logic/scripting/scripting.h:7,
                 from /home/bopik/build/VoxelEngine-Cpp/src/assets/Assets.cpp:9:
/home/bopik/build/VoxelEngine-Cpp/src/assets/../logic/scripting/lua/LuaState.h:9:2: ошибка: #error LuaJIT required
    9 | #error LuaJIT required
      |  ^~~~~
make[2]: *** [CMakeFiles/VoxelEngine.dir/build.make:76: CMakeFiles/VoxelEngine.dir/src/assets/Assets.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/VoxelEngine.dir/all] Ошибка 2
make: *** [Makefile:91: all] Ошибка 2`

Видел иссуе о замене libluajit на liblua и попытался сделать, но либо я не разобрался, либо просто не помогло.

**Comment by InfiniteCoder01** [comment]
Я "исправил" данную ошибку скачиванием LuaJit (`git clone https://luajit.org/git/luajit.git`), установкой куда-нибудь (`make && make install PREFIX=/some/path`) и заменой всех `find_package(Lua REQUIRED)` на
```
include_directories("/some/path/include/luajit-2.1/")
set(LUA_LIBRARIES "/some/path/lib/libluajit-5.1.a")
```
