### ISSUE TITLE
Компилирование на Linux.

### ISSUE THREAD

**Issue by TheQu1etOwl** [MihailRis/VoxelEngine-Cpp#2]
# Переходим в bash 
### Убедитесь что вы находитесь в директории движка
`$ sudo apt install libglfw3-dev libglfw3 libglew-dev libglm-dev  # установка зависимостей` 

`$ vi ./src/voxels/../files/WorldFiles.h  # я как тру хацкер редактрую в vi `

![image](https://user-images.githubusercontent.com/73735838/130258688-9baf7ccc-96c6-469a-896a-627b27178969.png)

`$ cd Debug`

`$ make # компилим`

`$ cd ..`

`$ ./Debug/voxel_engine # запускаем!`

P.S: у меня дистр kali linux ARM64

**Comment by shrpow** [comment]
не написано как выйти из vi (но я вышел)
