### ISSUE TITLE
Last Commit murders #176

### ISSUE THREAD

**Issue by InfiniteCoder01** [MihailRis/VoxelEngine-Cpp#201]
**Опишите ошибку**
Commit [bd5421d25415f117230997fa14b2a59a0ef115c1](https://github.com/MihailRis/VoxelEngine-Cpp/commit/bd5421d25415f117230997fa14b2a59a0ef115c1) убивает PR #176
```diff
diff --git a/res/scripts/stdlib.lua b/res/scripts/stdlib.lua
index d8397f5..9cb911f 100644
--- a/res/scripts/stdlib.lua
+++ b/res/scripts/stdlib.lua
@@ -131,7 +131,9 @@ events = {
 }
 
 function events.on(event, func)
-    events.handlers[event] = events.handlers[event] or {}
+    -- why an array? length is always = 1
+    -- FIXME: temporary fixed
+    events.handlers[event] = {} -- events.handlers[event] or {}
     table.insert(events.handlers[event], func)
 end
```

**Comment by MihailRis** [comment]
Нужен ответ на вопрос в коде.
Иначе это нововведение только плодит баги, не решая никаких иных задач

**Comment by InfiniteCoder01** [comment]
> Why an array? Length is always = 1

In https://github.com/MihailRis/VoxelEngine-Cpp/issues/173#issue-2172369110
> события в скриптах стоит не заменять, а вызывать все вместе

Позволяет дописывать дополнительное поведение блокам из других контент-паков

**Comment by MihailRis** [comment]
Что на данный момент в движке не является допустимым

**Comment by MihailRis** [comment]
Изначальный PR никак не связан с Issue на который ссылается, а также не содержит никаких упоминаний о предназначении массивов в очереди. Изменение будет окончательно удалено. Подобная возможность будет введена при необходимости позже, уже с более серьёзным подходом, не ломающий логику обработчиков событий (баг с несколькими срабатываниями события при перезаходе в мир, что воспроизводится уже с того коммита)
