### ISSUE TITLE
Планы на будущее

### ISSUE THREAD

**Issue by Stomarver** [MihailRis/VoxelEngine-Cpp#226]
Не стоит ли уже задумываться о системе партиклов?
Будешь ли делать жидкости и систему тиков?

**Comment by MihailRis** [comment]
- Частицы будут добавлены в одном из ближайших обновлений.
- Жидкости на данный момент имеют невысокий приоритет, что вероятно изменится после того, как станут реализуемы игровые режимы. 
- Система тактов реализована в некоторых аспектах. В ближайшем будущем будет реализована в более полном виде.
