### ISSUE TITLE
баг освещения

### ISSUE THREAD

**Issue by Nastiluse** [MihailRis/VoxelEngine-Cpp#231]
**Опишите ошибку**
Цветное/отсутствующее освещение от факела после установки и удаления другого источника света рядом

**Для воспроизведения**
Шаги для воспроизведения поведения:
1. Поставить факел
2. рядом(в радиусе 1-2 блоков) поставить лампу/лампочку/цветную лампу (эффект будет отличаться цветом)
3. убрать поставленную лампу/лампочку
4. См. ошибку

**Ожидаемое поведение**
сохранение освещения и его цвета от факела.

**Скриншоты**
![Deg38shSqz](https://github.com/MihailRis/VoxelEngine-Cpp/assets/160324386/1072d355-e475-40b7-b81a-5a1b99c26a2c)
![eyIH6Ogz9J](https://github.com/MihailRis/VoxelEngine-Cpp/assets/160324386/0d0b7aff-a247-40e6-aecc-776b29112a51)
![arwHfvTEgu](https://github.com/MihailRis/VoxelEngine-Cpp/assets/160324386/0e2dbcf0-5e86-4a25-ad7b-a36c75733d41)

**Техническая информация (заполните следующую информацию):**
  - ОС: Windows 10
  - Версия 0.21.1
  - GPU: AMD RX470 driver ver 24.3.1

**Дополнительный контекст**
Если поставить лампу, а после неё факел, то после удаления лампы ошибки нет

**Comment by Murka124** [comment]
После перезахода в мир освещение приходит в норму, баг можно воспроизвести ещё раз (движок уже версии v0.21.2)
