### ISSUE TITLE
Когда релиз под linux

### ISSUE THREAD

**Issue by steelswing** [MihailRis/VoxelEngine-Cpp#26]
Когда релиз под линукс:)????

**Comment by MihailRis** [comment]
На чистой системе запускается в две команды: установка библиотек и cmake, запуск run.sh
Но могу собрать deb пакет

**Comment by Justuser3310** [comment]
А что если... flatpak?
Будет намного больше доверия и установка в 2 счёта.

**Comment by Nediorg** [comment]
> А что если... flatpak? Будет намного больше доверия и установка в 2 счёта.

флатпаки ужасно медленные, да и по моему с ними будет много проблем

как вариант можно использовать тарболлы, либо appimage

**Comment by MihailRis** [comment]
Другие варианты добавлять лучше так-же, через github workflows
