### ISSUE TITLE
BUG Странное поведение отрисовки воды на большой дистанции

### ISSUE THREAD

**Issue by kirillzhosul** [MihailRis/VoxelEngine-Cpp#279]
**Опишите ошибку**
Вода отображается немного некоректно на далекой дистанции при приближении

**Ожидаемое поведение**
Вода отображается так же как и должна

**Скриншоты**
![image](https://github.com/user-attachments/assets/d70c9698-cdc8-4650-bc35-a1a4c83bbf8c)
![image](https://github.com/user-attachments/assets/479308dc-ef9b-4ad7-866a-96e61cad307f)

**Техническая информация (заполните следующую информацию):**
  - ОС: Windows 11
  - Версия 0.22

**Comment by MihailRis** [comment]
Это [норма](https://en.wikipedia.org/wiki/Z-fighting) в 3D графике, так как точность буфера глубины ограничена
