### ISSUE TITLE
Ошибка сборки движка 

### ISSUE THREAD

**Issue by Tet100** [MihailRis/VoxelEngine-Cpp#283]
**Опишите ошибку**
/home/Tet/VoxelEngine-Cpp/src/physics/PhysicsSolver.cpp: In member function ‘void PhysicsSolver::removeSensor(Sensor*)’:
/home/Tet/VoxelEngine-Cpp/src/physics/PhysicsSolver.cpp:278:44: error: cannot convert ‘std::vector<Sensor*>::iterator’ to ‘const char*’
  278 |     sensors.erase(std::remove(sensors.begin(), sensors.end(), sensor), sensors.end());
      |                               ~~~~~~~~~~~~~^~
      |                                            |
      |                                            std::vector<Sensor*>::iterator
In file included from /usr/include/c++/14.1.1/cstdio:42,
                 from /usr/include/c++/14.1.1/ext/string_conversions.h:45,
                 from /usr/include/c++/14.1.1/bits/basic_string.h:4154,
                 from /usr/include/c++/14.1.1/string:54,
                 from /home/Tet/VoxelEngine-Cpp/src/physics/Hitbox.hpp:8,
                 from /home/Tet/VoxelEngine-Cpp/src/physics/PhysicsSolver.hpp:4,
                 from /home/Tet/VoxelEngine-Cpp/src/physics/PhysicsSolver.cpp:1:
/usr/include/stdio.h:158:32: note:   initializing argument 1 of ‘int remove(const char*’
  158 | extern int remove (const char *__filename) __THROW;
      |                    ~~~~~~~~~~~~^~~~~~~~~~
make[2]: *** [CMakeFiles/VoxelEngine.dir/build.make:2022: CMakeFiles/VoxelEngine.dir/src/physics/PhysicsSolver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/VoxelEngine.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Для воспроизведения**
Шаги для воспроизведения поведения:
1. Действовать инструкции

  - ОС: Arch Linux

**Comment by MihailRis** [comment]
Решил ли проблему последний [коммит](https://github.com/MihailRis/VoxelEngine-Cpp/commit/c12619a8d61d8bf9b0d7743d1960f969306e0623)?
