### ISSUE TITLE
Build #959 instant crash

### ISSUE THREAD

**Issue by Serebr1k** [MihailRis/VoxelEngine-Cpp#316]
When I run .exe it opens and almost instantly closes

1. Download build #959
2. Unpack
3. Run
4. Crash

  - Windows 11 Licenced Pro
  - Build #959
  - RTX 3060 6gb
  - 8gb RAM

**Comment by Serebr1k** [comment]
Sowwy my english is bad

**Comment by MihailRis** [comment]
Does this build work? https://github.com/MihailRis/VoxelEngine-Cpp/actions/runs/11444687702/artifacts/2083603029
