### ISSUE TITLE
BUG pipe colision

### ISSUE THREAD

**Issue by Sergwest585** [MihailRis/VoxelEngine-Cpp#348]
Можно ходить сквозь трубу, повёрнутую боком

Шаги для воспроизведения поведения:
Установите трубу на уровне головы, повернув её в любом направление, но не вверх
Отключите полёт (если включён)
Убедитесь, что ваша координата y = x.93 (не .92, не .94)
Пройдите сквозь трубу

Ожидается, что пройти сквозь трубу нельзя
![bug](https://github.com/user-attachments/assets/47512dbe-28d3-4a07-9346-2bec6b2a3fd9)

Техническая информация:
  - ОС: Linux (void)
  - Версия: 0.23

**Comment by MihailRis** [comment]
Было исправлено сегодня
