### ISSUE TITLE
BUG Sand falling block +x/+z

### ISSUE THREAD

**Issue by Sergwest585** [MihailRis/VoxelEngine-Cpp#359]
Песок не видит хитбоксы плоских блоков, смотрящих на +координату

Шаги для воспроизведения поведения:
1. поставте две двери или панели так, чтобы одна смотрела на +координату, другая в обратную сторону
2. поставте на них по блоку и блок песка сверху (скриншот 1)
3. сломайте первые блоки
4. результат: один разместится на двери/панели, другой упадёт сквозь (скриншот 2)

Ожидаемое поведение:
одинаковое поведение

1:
![2024-11-08T23:21:19,236641872+03:00](https://github.com/user-attachments/assets/ff977169-283a-48c8-86fc-53854675f116)

2:
![2024-11-08T23:21:49,853227271+03:00](https://github.com/user-attachments/assets/83e4d9f8-9391-48fc-b2d8-85acbcfc41c2)

Техническая информация:
  - ОС: Void linux
  - Версия 0.24

С одной стороны любопытное свойство, с другой стороны баг

**Comment by MihailRis** [comment]
Исправлено. Причина в том, что хитбокс падающего блока был меньше самого блока, как раз на толщину двери. Поэтому при падении с одной стороны он задевал дверь только из-за погрешности.
