### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jestsi** [MihailRis/VoxelEngine-Cpp#363]
Не очень оптимизированно, нужно поработать над сборщиком мусора. Был момент отлетел далеко, тепнулся на блоков 2000 в другое место. И видел как та местность с которой я тепнулся все еще загружена. 

И еще, я заметил если кидать предметы, то они падают всегда четко под игроком. 

10 гигов оперативки 
![image](https://github.com/user-attachments/assets/819ae62b-0b0b-474c-9428-8c4213dcd9a3)

**Comment by MihailRis** [comment]
Какая дальность загрузки?

**Comment by jestsi** [comment]
> Какая дальность загрузки?
Максимальная 😅

**Comment by jestsi** [comment]
а еще с 5к блоков от 0 по x, z появляются артифакты. Чем дальше тем сильнее

**Comment by MihailRis** [comment]
Максимальная дальность - 80 чанков.
Диаметр области `80 * 2 + 1 = 161` чанк.
Итоговое число чанков при полной прогрузке: `161 * 161 = 25 921`
Один воксель (блок) занимает 4 байта памяти. В чанке их `256 * 16 * 16 = 65 536`.
Плюс 2 байта к каждому вокселю - освещение.
Итог - чанк занимает около `65 536 * (4 + 2) = 393 216 байта`.
Умножаем на число чанков и получаем `10 192 551 936 байт`, что как раз примерно 10 ГБ. А чанки ещё и не единственное, на что идёт память.

**Comment by MihailRis** [comment]
Насчет остального.
- раз при телепортации старые чанки не были скрыты туманом, значит они всё ещё находились в зоне прогрузки, так что здесь всё корректно.
- выброшенные предметы получают, кроме силы броска, ещё и линейную скорость игрока, так что здесь тоже всё корректно.
- про артефакты на больших расстояниях давно известно, в будущем это будет исправлено, но сейчас, приоритет у этой задачи невысокий.
