### ISSUE TITLE
Блок panel некорректно отображается.

### ISSUE THREAD

**Issue by A-lex-Ra** [MihailRis/VoxelEngine-Cpp#37]
Это баг или ещё не реализовано? Наведение тоже срабатывает если курсор наведён в любое место этого вокселя.
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/cc92cb3b-11c7-4ece-98b6-ca0568c5f9a3)
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/4cfb5065-ffb3-4d43-b993-c60f1085172f)

**Comment by MihailRis** [comment]
поэтому и wip, что он ещё в разработке
