### ISSUE TITLE
Incorrect translucent faces color blending.

### ISSUE THREAD

**Issue by MihailRis** [MihailRis/VoxelEngine-Cpp#371]
Current color blending configuration shows incorrect results when two translucent faces overlapping in front of dark background.

Color blending is configured in [DrawContext.cpp](https://github.com/MihailRis/VoxelEngine-Cpp/blob/255c49916cf61c6f44d5f9b4f090b584eb88871c/src/graphics/core/DrawContext.cpp#L14).

Screenshot: hole sides should be darker than the surface when blending with it. Right half of the screenshot is correct.
![screenshot-2024-11-17_08-20-48](https://github.com/user-attachments/assets/31c1113a-6a71-426f-88dc-10d73755ca5d)

**Comment by MihailRis** [comment]
wait a second...
![2024-11-20_07 05 50](https://github.com/user-attachments/assets/bfbe5596-00af-48ca-a9b4-a65ffc949c8f)

**Comment by RichardTry** [comment]
It's correct. Sides are lighter cos they adds bright in compare with background.
