### ISSUE TITLE
BUG in pages/main

### ISSUE THREAD

**Issue by QuFlax** [MihailRis/VoxelEngine-Cpp#382]
**Опишите ошибку**
Ошибка в pages/main
[E] 2024/11/24 18:10:20.569+0300 [                 lua] [string "core:layouts/pages/main.lua"]:4: document 'core:pages/main' has no element with id 'worlds'
stack traceback:
        [C]: in function '__index'
        [string "core:layouts/pages/main.lua"]:4: in function 'func'
        [string "core:scripts/stdlib.lua"]:57: in function <[string "core:scripts/stdlib.lua"]:50>
        [C]: in function 'close_world'
        [string "res\layouts/pages/pause.xml"]:1: in main chunk

**Для воспроизведения**
Шаги для воспроизведения поведения:
1. Создать мир
2. Вийти с мира
3. См. ошибку

**Скриншоты**
![image](https://github.com/user-attachments/assets/9cc2611c-1562-4690-9e7a-089491e9d123)

**Техническая информация (заполните следующую информацию):**
  - ОС: Windows 10 PRO 22H2
  - Версия 0.25

**Comment by MihailRis** [comment]
Скрипта res/layouts/pages/main.xml.lua (как и res/layouts/pages/main.lua) не существует
