### ISSUE TITLE
Позиционирование камеры

### ISSUE THREAD

**Issue by A-lex-Ra** [MihailRis/VoxelEngine-Cpp#40]
При полёте вверх-вниз в чит-моде, камера сильно качается после остановки, а затем может и упасть куда-то "в ноги" (а может не упасть, раньше только раскачивалась).

P.S. tested in VirtualBox Ubuntu 22.04.03LTS со слабыми характеристиками
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/81af3de5-d01c-4e26-9f86-7435b54f32b6)

**Comment by Stomarver** [comment]
+++, лучше вообще эту пружину убрать.
