### ISSUE TITLE
ENHANCEMENT  Global ContentPacks for Main Menu and Settings menu

### ISSUE THREAD

**Issue by TheShlyukov** [MihailRis/VoxelEngine-Cpp#415]
**Связан ли ваш запрос на добавление функции с проблемой? Пожалуйста, опишите.**
Сейчас КонтентПаки распространяются только на игровой процесс (на миры). Хотелось бы иметь возможность добавлять контентпаки на уровне главного меню и настроек.

**Опишите желаемое решение**
Добавить возможность применять контент паки на уровне главного меню или настроек. Это позволит: 
1. Изменить фон главного экрана
2. Добавить фоновую музыку в главный экран (на данный момент это можно реализовать только в игровом процессе)
3. Добавить настройки контентпаков во вкладку настроек (например, чтобы можно было изменить привязки клавиш для функции контентпака или отдельную вкладку в настройках графики для настройки графического контентпака (по типу Optifine))
4. Изменять расположение/добавлять/скрывать кнопки в главном меню (why not)
И.т.д.

**Опишите альтернативы, которые вы рассматривали**
А такие есть разве?
**Дополнительный контекст**
В первую очередь, я предлагаю это нововведение для того чтобы реализовать фоновую музыку для игры. Она сделает игру (основанную на этом движке) более атмосферной.

P.s. кста, Вам композиторы не нужны?)

**Comment by MihailRis** [comment]
Сейчас меню является своего рода лаунчером, меню движка, а не игры, отдельным от основного состояния работы движка. Когда в базовый пак будет добавлено **игровое меню**, проблема будет решена без дополнительных нововведений.

**Comment by TheShlyukov** [comment]
Хорошо, у меня есть вопрос не по теме issue:
Можно ли приравнивать VoxelEngine к Игре, или это только основа для другой игры?

**Comment by MihailRis** [comment]
Это движок. Весь контент и большинство игровых механик (кроме самых базовых) реализуется через контент-паки.
Система сборок / игр будет введена в ближайшем будущем, как и редактор, что уже частично реализуется в разных разделах консоли.

**Comment by TheShlyukov** [comment]
Тогда ждём следующих обновлений)
