### ISSUE TITLE
Не собирается проект на windows из-за lua.hpp

### ISSUE THREAD

**Issue by Borodinskiy** [MihailRis/VoxelEngine-Cpp#425]
Пишет ошибку в отсутствии lua.hpp, хотя в vsproj.json присутствует luajit. Добавил рядом зависимость lua, и теперь вообще не видит ни lua, ни luajit. -_-

**Comment by Borodinskiy** [comment]
![image](https://github.com/user-attachments/assets/0574cfe2-390f-448d-9204-a66cdb508716)

![image](https://github.com/user-attachments/assets/5848a2f8-080d-4996-8a7e-20607c264a23)

![image](https://github.com/user-attachments/assets/7d7df2ff-4c6e-4209-9a53-43df296e6845)

**Comment by MihailRis** [comment]
Стоит проверить ветку [headless-mode](https://github.com/MihailRis/VoxelEngine-Cpp/tree/headless-mode), там процесс сборки проекта под Windows уже изменен, как и инструкция в README,

**Comment by Borodinskiy** [comment]
Проект собрался, спасибо.
