### ISSUE TITLE
У aabb моделей некорректо отображается текстура

### ISSUE THREAD

**Issue by MrMeOwO** [MihailRis/VoxelEngine-Cpp#49]
![screenshot-2023-12-10_22-48-21](https://github.com/MihailRis/VoxelEngine-Cpp/assets/99050829/94939494-8fc6-44bf-bb3c-e14df7ef36f1)
хитбокс и текстура не совпадают, скорее всего отсчёт по x начинается не там. с z всё нормально.
содержимое файла:
`{
    "texture-faces": [
        "pipe_side",
        "pipe_side",
        "pipe_hole",
        "pipe_hole",
        "pipe_side",
        "pipe_side"
    ],
    "model": "aabb",
    "hitbox": [0.5, 0.0, 0.0, 0.5, 0.5, 0.5],
    "light-passing": true,
    "rotation": "pipe"
}
`

**Comment by MihailRis** [comment]
Исправлено последним коммитом. Позже обновлю и exe файл
