### ISSUE TITLE
Предложение: Добавить уже наконец языковые файлы.

### ISSUE THREAD

**Issue by N08I40K** [MihailRis/VoxelEngine-Cpp#52]
В теории я могу попробовать ближайшее время сделать основу локализации, но не могу ничего обещать)

Глаза режет(
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/55545594/bc99632c-039e-4e2f-a880-34da73dfaa46)

**Comment by IosifShmidt** [comment]
В 7bf70bb была добавлена поддержка локализаций. Возможно стоило бы взять готовый формат локализации типа gettext.
