### ISSUE TITLE
[TEXTURES] одна сторона AABB-блока всегда рендерится перевёрнутой

### ISSUE THREAD

**Issue by A-lex-Ra** [MihailRis/VoxelEngine-Cpp#53]
это всегда первая сторона из json-а блока.
![screenshot-2023-12-11_12-12-13](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/c49b57b3-a2d4-40f3-8d57-fc4e7af514ae)
![screenshot-2023-12-11_12-13-40](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/c609513a-8064-43b0-a071-d527727ae77b)
![screenshot-2023-12-11_12-14-02](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/3ca6805c-c825-4fdc-91d5-96293e68c153)

**Comment by A-lex-Ra** [comment]
а, это уже записано в TODO...

**Comment by A-lex-Ra** [comment]
хотя нет, там речь про laxisZ

**Comment by A-lex-Ra** [comment]
я понимаю, что WIP, но сообщать о багах всё равно нужно ведь

**Comment by MihailRis** [comment]
> я понимаю, что WIP, но сообщать о багах всё равно нужно ведь
а вот этот баг уже воспроизвести не получается
какой хитбокс, профиль вращения?

**Comment by MihailRis** [comment]
Перевернул сторону

**Comment by A-lex-Ra** [comment]
у меня тоже не воспроизводится, так что пока закрою issue
