### ISSUE TITLE
Миграция на Vulkan API?

### ISSUE THREAD

**Issue by A-lex-Ra** [MihailRis/VoxelEngine-Cpp#58]
Вулкан – прямое продолжение OpenGL, но более оптимизирован под многоядерность, быстрее рендерит но, кажется, многословнее в написании. Зато простор для оптимизации и более современные технологии.. worth it? думаю, что да

**Comment by MihailRis** [comment]
https://github.com/MihailRis/VoxelEngine-Cpp/pull/33

**Comment by A-lex-Ra** [comment]
Понял, спасибо.
