### ISSUE TITLE
[CRITICAL] Русские названия миров в винде

### ISSUE THREAD

**Issue by A-lex-Ra** [MihailRis/VoxelEngine-Cpp#62]
Если создать мир с русским названием, а затем попытаться "Save and quit", то либо падение, либо выход в меню, но в любом случае название кодируется-декодируется некорректно, так что затем зайти в мир невозможно и есть большая вероятность упасть при инициализации main_menu (если в названии есть буква ц, например)
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/97386075/3351953b-db26-43db-95fd-1d354ab3a10a)

**Comment by A-lex-Ra** [comment]
Эта проблема была ещё до добавления локализации.

**Comment by A-lex-Ra** [comment]
wchar_t и, соответственно, wstring зависят от компилятора, и в MSVC wchar_t имеет размер 16 бит, реализуя UTF-16, которым никто кроме винды не пользуется... наверное поэтому и баги

**Comment by A-lex-Ra** [comment]
пофиксил кодом отсюда: https://gist.github.com/vurdalakov/29d05d1820a241e3ba482ceaf28af2de
но stringutil определённо нужно отрефакторить.

**Comment by A-lex-Ra** [comment]
посидел ещё, сделал наконец полностью рабочим, но затем понял, что совместимость теряется, если мы храним название мира не-универсальным способом. Нужно тогда кодировку названия прописывать в json-e, видимо, чтобы парсить.

**Comment by A-lex-Ra** [comment]
"Почти" означает, что весь ui кроме названий миров полетел ко всем чертям :/
Надеюсь на помощь

**Comment by MihailRis** [comment]
Исправил последним коммитом

**Comment by A-lex-Ra** [comment]
Впечатляет! Исправил одной строчкой!
