### ISSUE TITLE
Утечка памяти

### ISSUE THREAD

**Issue by alex-sandalov** [MihailRis/VoxelEngine-Cpp#75]
```
LevelController::LevelController(EngineSettings& settings, Level* level) 
    : settings(settings), level(level) {
    blocks = new BlocksController(level, settings.chunks.padding);
    chunks = new ChunksController(level, settings.chunks.padding);
    player = new PlayerController(level, settings, blocks);

    scripting::on_world_load(level);
}

LevelController::~LevelController() {
    scripting::on_world_quit();
    delete player;
    delete chunks;
}
```

**Comment by alex-sandalov** [comment]
Вроде тут утечка памяти, я не нашел в коде где удаляется blocks, также вопрос, почему Вы не пользуетесь умными указателями?

**Comment by MihailRis** [comment]
Исправлено

**Comment by suprohub** [comment]
> Вроде тут утечка памяти, я не нашел в коде где удаляется blocks, также вопрос, почему Вы не пользуетесь умными указателями?

Да кто его знает, лень им

**Comment by MihailRis** [comment]
> > Вроде тут утечка памяти, я не нашел в коде где удаляется blocks, также вопрос, почему Вы не пользуетесь умными указателями?
> 
> Да кто его знает, лень им

???
