### ISSUE TITLE
Легальный X-Ray

### ISSUE THREAD

**Issue by AmnesiaXxXxX** [MihailRis/VoxelEngine-Cpp#77]
Если сделать "непрорачное" стекло, то текстуры за ним не прорисовываются и видно пустые блоки сквозь пустоту
Код блока:
`{
    "texture": "glass",
    "draw-group": 2,
    "light-passing": false
}`

![screenshot-2023-12-30_16-54-36](https://github.com/MihailRis/VoxelEngine-Cpp/assets/92972232/3f519bc8-08b8-4ab9-8e7b-caa911ba0de8)

**Comment by A-lex-Ra** [comment]
Это не баг, ты волен создавать с помощью модов что угодно. Возможно, если это будет востребованно, в будущем сделаем автоматическую проверку на прозрачность.
