### ISSUE TITLE
Фастревел

### ISSUE THREAD

**Issue by AmnesiaXxXxX** [MihailRis/VoxelEngine-Cpp#78]
Если в ноуклипе залететь в землю и выключил ноуклип пойти в какую то из сторон, начинает относить до 4096 координаты по x.

https://github.com/MihailRis/VoxelEngine-Cpp/assets/92972232/49278021-dcff-4fbc-9a95-b69e246f43ac

**Comment by A-lex-Ra** [comment]
вот тут согласен, физику застревания в блоках надо сделать адекватной

**Comment by A-lex-Ra** [comment]
хотя, конечно, в каком-нибудь "Выживании" noclip доступен не будет, такая дичь происходить не должна в принципе (я сам протестил, баг не единичный)

**Comment by Stomarver** [comment]
> хотя, конечно, в каком-нибудь "Выживании" noclip доступен не будет, такая дичь происходить не должна в принципе (я сам протестил, баг не единичный)

да даже банально если будут физические блоки которые будут тебя выталкивать

**Comment by MihailRis** [comment]
было исправлено в 0.17
