### ISSUE TITLE
Баг с выталкиванием из хитбокса

### ISSUE THREAD

**Issue by AmnesiaXxXxX** [MihailRis/VoxelEngine-Cpp#79]
По стандарту размеры блока ограничены 1х1х1, если выставить размер хитбокса блока например 2х2х2 то он будет выталкивать только до края хитбокса, при этом если выставить монструозные значения, как показано на видео, откинет настолько далеко, что мира там даже не существует.

https://github.com/MihailRis/VoxelEngine-Cpp/assets/92972232/abd1c654-3f94-4cd1-8c7b-94bc6df9924b

**Comment by MihailRis** [comment]
так, и в чём же заключается проблема?

**Comment by Sinus44** [comment]
@MihailRis, возможно он имел ввиду ввести ограничения для модификаций. Я честно, не вижу в этом смысла

**Comment by MihailRis** [comment]
подобные ограничения имеют смысл в фронтенде редакторов, загрузчик же проверяет корректность критических параметров, ошибку в которых легко допустить ненамеренно
