### ISSUE TITLE
Не работает на Arch

### ISSUE THREAD

**Issue by Stomarver** [MihailRis/VoxelEngine-Cpp#98]
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/90529479/284ae404-f234-46df-959a-94c06f4109f9)
Зависимости установил, LuajIT тоже, запускал 0.16, предпоследние акшины тоже.

**Comment by Lintech-1** [comment]
Подтверждаю! только у меня не просто чёрный экран, а картинка артефачит, но консоль в логах ничего не пишет
![image](https://github.com/MihailRis/VoxelEngine-Cpp/assets/81373196/6a459dfe-6372-4567-ba33-a946cdedc6fd)

**Comment by Stomarver** [comment]
> Подтверждаю! только у меня не просто чёрный экран, а картинка артефачит, но консоль в логах ничего не пишет ![image](https://private-user-images.githubusercontent.com/81373196/297427776-6a459dfe-6372-4567-ba33-a946cdedc6fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDU4NjAsIm5iZiI6MTcwNTUwNTU2MCwicGF0aCI6Ii84MTM3MzE5Ni8yOTc0Mjc3NzYtNmE0NTlkZmUtNjM3Mi00NTY3LWJhMzMtYTk0NmNkZWRjNmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OTFhNDBiOTZiNjljNzlkNGNlYmRkNDhmNDkxY2JlODE1NDliNTc2YjA5MDI4MjU5MzRmZTE5ZTBkMzc1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNN3uKKC9ZTDBVPK4vjDbEWM72hmqdALKXDv6wF9jOQ)

это Кде или Циннамон?

**Comment by Lintech-1** [comment]
> > Подтверждаю! только у меня не просто чёрный экран, а картинка артефачит, но консоль в логах ничего не пишет ![image](https://private-user-images.githubusercontent.com/81373196/297427776-6a459dfe-6372-4567-ba33-a946cdedc6fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDU4NjAsIm5iZiI6MTcwNTUwNTU2MCwicGF0aCI6Ii84MTM3MzE5Ni8yOTc0Mjc3NzYtNmE0NTlkZmUtNjM3Mi00NTY3LWJhMzMtYTk0NmNkZWRjNmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OTFhNDBiOTZiNjljNzlkNGNlYmRkNDhmNDkxY2JlODE1NDliNTc2YjA5MDI4MjU5MzRmZTE5ZTBkMzc1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNN3uKKC9ZTDBVPK4vjDbEWM72hmqdALKXDv6wF9jOQ)
> 
> это Кде или Циннамон?

кеды

**Comment by Stomarver** [comment]
> > > Подтверждаю! только у меня не просто чёрный экран, а картинка артефачит, но консоль в логах ничего не пишет ![image](https://private-user-images.githubusercontent.com/81373196/297427776-6a459dfe-6372-4567-ba33-a946cdedc6fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDU4NjAsIm5iZiI6MTcwNTUwNTU2MCwicGF0aCI6Ii84MTM3MzE5Ni8yOTc0Mjc3NzYtNmE0NTlkZmUtNjM3Mi00NTY3LWJhMzMtYTk0NmNkZWRjNmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OTFhNDBiOTZiNjljNzlkNGNlYmRkNDhmNDkxY2JlODE1NDliNTc2YjA5MDI4MjU5MzRmZTE5ZTBkMzc1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dNN3uKKC9ZTDBVPK4vjDbEWM72hmqdALKXDv6wF9jOQ)
> > 
> > 
> > это Кде или Циннамон?
> 
> кеды

пон, тогда скорее всего проблема в гноме (у меня)

**Comment by farfind-gpt** [comment]
похожая ситуация: у меня Manjaro, скачал AppImage (версия 0.18), при запуске чёрный экран, при изменении размера окна артефакты. ничего дополнительно не устанавливал: вроде-бы AppImage'ы обычно включают всё, что нужно (поправьте, пожалуйста, если это не так). в консоли останавливается на "-- loading settings", после закрытия окна выводит "GL Vendor: %"

полный вывод консоли:
```
userfiles folder: /home/farfind/.voxeng
resources folder: /tmp/.mount_VoxelEwdxBz0/usr/share/VoxelEngine/res
unexpected token
-- loading settings
GL Vendor: %
```

( забавно, но версия для windows отлично запустилась с помощью wine :) )

**Comment by Stomarver** [comment]
> похожая ситуация: у меня Manjaro, скачал AppImage (версия 0.18), при запуске чёрный экран, при изменении размера окна артефакты. ничего дополнительно не устанавливал: вроде-бы AppImage'ы обычно включают всё, что нужно (поправьте, пожалуйста, если это не так). в консоли останавливается на "-- loading settings", после закрытия окна выводит "GL Vendor: %"
> 
> полный вывод консоли:
> 
> ```
> userfiles folder: /home/farfind/.voxeng
> resources folder: /tmp/.mount_VoxelEwdxBz0/usr/share/VoxelEngine/res
> unexpected token
> -- loading settings
> GL Vendor: %
> ```
> 
> ( забавно, но версия для windows отлично запустилась с помощью wine :) )

да, я тоже через вайн запустил и всё работает. Скорее всего нужно собрать что бы заработал

**Comment by farfind-gpt** [comment]
> да, я тоже через вайн запустил и всё работает. Скорее всего нужно собрать что бы заработал

действительно, когда сам собрал прекрасно запустилось, спасибо за совет!

**Comment by Stomarver** [comment]
> > да, я тоже через вайн запустил и всё работает. Скорее всего нужно собрать что бы заработал
> 
> действительно, когда сам собрал прекрасно запустилось, спасибо за совет!

Спасибо за то что проверил, щас тоже попробую

**Comment by InfiniteCoder01** [comment]
AppImage на Arch точно сломан, так же, как и docker на Wayland.

**Comment by Stomarver** [comment]
> AppImage на Arch точно сломан, так же, как и docker на Wayland.

Да не сказать. Пока все аппимаджи которые я скачивал работали на арч.

**Comment by MihailRis** [comment]
В генерируемом AppImage используется X11 версия GLFW
В принципе, можно добавить автоматическую сборку и с Wayland версией

**Comment by Stomarver** [comment]
> В генерируемом AppImage используется X11 версия GLFW В принципе, можно добавить автоматическую сборку и с Wayland версией

мем в том что и в x11 я тоже пытался запустить, но не вышло. GLFW x11 тоже ставил

**Comment by Stomarver** [comment]
> В генерируемом AppImage используется X11 версия GLFW В принципе, можно добавить автоматическую сборку и с Wayland версией

Кароч забей на аппииадж, сами соберём, не маленькие :) (на крайняк сделай флатпак, его проще адаптировать и поддерживать)

**Comment by Stomarver** [comment]
Да закрой уже, проблема то считай решена

**Comment by MihailRis** [comment]
уже закрыл, когда исправил
сейчас просто убрал из закрепа
